# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: matheus25caio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: polllychat
service: my-chatbot-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  memorySize: 128
  timeout: 30

functions:
  LambdaGerenciarPerfil:
    handler: lambdas/LambdaGerenciarPerfil/handler.handler
    events:
      - lex:
          name: MeuChatBot
          alias: "production"
          description: "Bot para gerenciar o perfil do usuário"
      - http:
          path: /perfil
          method: post
          cors: true

  LambdaFuncionalidades:
    handler: lambdas/LambdaFuncionalidades/handler.handler
    events:
      - lex:
          name: MeuChatBot
          alias: "production"
          description: "Funções de funcionalidades como transcrição e tradução"
      - http:
          path: /funcionalidades
          method: post
          cors: true

resources:
  Resources:
    MeuChatBot:
      Type: AWS::Lex::Bot
      Properties:
        Name: MeuChatBot
        Locale: en-US
        Intents:
          - IntentName: Saudacao
            IntentVersion: "1"
          - IntentName: VerificarPerfil
            IntentVersion: "1"
          - IntentName: CriarPerfil
            IntentVersion: "1"
          - IntentName: TranscreverAudio
            IntentVersion: "1"
          - IntentName: TraduzirTexto
            IntentVersion: "1"
        ClarificationPrompt:
          MaxAttempts: 2
          Messages:
            - Content: "Desculpe, não entendi. Pode repetir?"
              ContentType: PlainText
        AbortStatement:
          Messages:
            - Content: "Lamento, mas não consigo ajudar com isso no momento."
              ContentType: PlainText

  Outputs:
    APIURL:
      Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/"
      Description: "URL da API Gateway"
